# Generated by Django 4.1 on 2022-09-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_my_stuff', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='item description'),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='item name', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='category description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='category name', max_length=100),
        ),
    ]
